// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetworkMonitoring.Database.DBC;

#nullable disable

namespace NetworkMonitoring.Database.Migrations
{
    [DbContext(typeof(NetworkMonitoringDbContext))]
    [Migration("20240523114418_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NetworkMonitoring.Domain.Account.SystemObject", b =>
                {
                    b.Property<int>("SystemObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemObjectID"));

                    b.Property<int>("ParentID")
                        .HasColumnType("int");

                    b.Property<string>("SystemObjectRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemObjectTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SystemObjectID");

                    b.ToTable("Sys_SystemObject");
                });

            modelBuilder.Entity("NetworkMonitoring.Domain.Account.SystemUser", b =>
                {
                    b.Property<int>("SystemUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemUserID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SystemUserGroupID")
                        .HasColumnType("int");

                    b.Property<string>("SystemUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemUserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SystemUserID");

                    b.HasIndex("SystemUserGroupID");

                    b.ToTable("Sys_SystemUser");
                });

            modelBuilder.Entity("NetworkMonitoring.Domain.Account.SystemUserAccessRole", b =>
                {
                    b.Property<Guid>("SystemUserAccessRolesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SystemObjectID")
                        .HasColumnType("int");

                    b.Property<int>("SystemUserGroupID")
                        .HasColumnType("int");

                    b.HasKey("SystemUserAccessRolesID");

                    b.HasIndex("SystemObjectID");

                    b.HasIndex("SystemUserGroupID");

                    b.ToTable("Sys_SystemUserAccessRole");
                });

            modelBuilder.Entity("NetworkMonitoring.Domain.Account.SystemUserGroup", b =>
                {
                    b.Property<int>("SystemUserGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemUserGroupID"));

                    b.Property<string>("SystemUserGroupTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SystemUserGroupID");

                    b.ToTable("Sys_SystemUserGroup");
                });

            modelBuilder.Entity("NetworkMonitoring.Domain.Account.SystemUser", b =>
                {
                    b.HasOne("NetworkMonitoring.Domain.Account.SystemUserGroup", "SystemUserGroup")
                        .WithMany()
                        .HasForeignKey("SystemUserGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUserGroup");
                });

            modelBuilder.Entity("NetworkMonitoring.Domain.Account.SystemUserAccessRole", b =>
                {
                    b.HasOne("NetworkMonitoring.Domain.Account.SystemObject", "SystemObject")
                        .WithMany()
                        .HasForeignKey("SystemObjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetworkMonitoring.Domain.Account.SystemUserGroup", "SystemUserGroup")
                        .WithMany()
                        .HasForeignKey("SystemUserGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemObject");

                    b.Navigation("SystemUserGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
